name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: |
        git clone --recursive https://github.com/armory3d/iron_examples
        cd iron_examples/mesh
        git clone --recursive https://github.com/kode/Kha
        git clone https://github.com/Kode/nodejs_bin --depth 1
    - name: Compile
      run: |
        cd iron_examples/mesh
        nodejs_bin/node-linux64 Kha/make.js -g opengl
