name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get iron_examples
      run: git clone --recursive https://github.com/armory3d/iron_examples
    - name: Get Kha
      run: git clone --recursive https://github.com/kode/Kha
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin --depth 1
    - name: Compile
      run: nodejs_bin/node-linux64 Kha/make.js -g opengl --from iron_examples/mesh
